### ISSUE TITLE
Could you write minimal getting started?

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/ovm.tz#1]
I wanna try this project.

Thank you.

**Comment by daiki44** [comment]
@syuhei176 
Getting started is here.
https://github.com/cryptoeconomicslab/ovm.tz/blob/master/contracts/README.md

Then, you should install LIGO that is the smart contract language of Tezos.

How to install LIGO?
-> https://ligolang.org/docs/setup/installation.html

**Comment by syuhei176** [comment]
@daiki44 Thanks!
