### ISSUE TITLE
Tezos abi-adaptor compilation test into Typescript SDK

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/ovm.tz#11]
Require #10

Rust's abi-util has to be run on the Typescript environment in order to integrate with React Native.

**Comment by shogochiai** [comment]
@daiki44 Once we implement #10, we just need to make sure we can target the Typescript.

And we can implement Typescript SDK by using that compiled module.

Is this recognition correct?

**Comment by daiki44** [comment]
> And we can implement Typescript SDK by using that compiled module.
@shogochiai 
Probably we can do that like this page.
https://medium.com/@atulanand94/using-rust-modules-for-javascript-web-development-part-3-3-nodejs-7c71e4ae23fe

Is that correct? @syuhei176

**Comment by syuhei176** [comment]
No, you should write serializer, events-watcher, and contract-wrapper with Typescript.

**Comment by daiki44** [comment]
Got it. Thank you!
