### ISSUE TITLE
Amendment proposal of Dynamic Call

### ISSUE THREAD

**Issue by daiki44** [cryptoeconomicslab/ovm.tz#17]
Whether is this required or not?
* If it is required
    * How to write it by the end of amendment?
* If it is not required
    * How to implement Dynamic Call instead of it?

Related to: #13

**Comment by shogochiai** [comment]
I'm not sure if it's required but it's already planned or implemented AFAIK.
I'll bring evidence of it.

**Comment by daiki44** [comment]
@shogochiai 
Is this necessary for this project?

**Comment by syuhei176** [comment]
I think it depends on points below.
1. max contract size. If max contract size of tezos is enough big, we can include all predicates to one contract.
2. address type of tezos enoder. If we don't use dynamic call, predicateAddress shouldn't be "address". We need to hack Coder of tezos.

**Comment by daiki44** [comment]
https://ligolang.org/docs/next/advanced/entrypoints-contracts/#cross-contract-calls
