### ISSUE TITLE
Try bytes_unpack

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/ovm.tz#36]
As per team ligo, current latest PascaLIGO (which called "next" and based on dev branch) has unpack capability.

**Comment by shogochiai** [comment]
`ligo compile-expression 'bytes_unpack("bytes")' -s pascaligo`

would be a simple test command.

**Comment by shogochiai** [comment]
Likely not yet.

```
$ ligo compile-expression 'bytes_unpack' -s pascaligo
#=> in file "", line 1, characters 0-12. unbound variable:  {"variable":"bytes_unpack","environment":"- E[]\tT[] ]","location":"in file \"\", line 1, characters 0-12"}
```

**Comment by shogochiai** [comment]
`unpack` fix was [already on the dev branch](https://gitlab.com/ligolang/ligo/commits/dev).

Docukerhub's `ligolang/ligo#next` [has already been updated](https://hub.docker.com/r/ligolang/ligo/tags) 15hours ago.

It should be pulled to local docker environment...

**Comment by syuhei176** [comment]
write test for bytes_unpack, we'll use it later maybe.

**Comment by shogochiai** [comment]
Lemme close this issue and reopen new issue for more detailed contents.

![Screen Shot 2020-01-09 at 18 50 01](https://user-images.githubusercontent.com/4891004/72129874-291eb280-33bb-11ea-9861-d490bd183b52.png)
