### ISSUE TITLE
Amendment proposal of keccak256 

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/ovm.tz#6]
For interoperability https://github.com/cryptoeconomicslab/ovm.tz/issues/5

Whether is this required or not?
* If it is required
    * How to write it by the end of amendment?
* If it is not required
    * How to implement Keccak256 instead of it?

How to amendment it?
1. Port keccak256 into ocaml-hacl
2. Put ocaml-hacl on Tezos
3. Correspond the michelson bytecode
4. Add a LIGO reserved function
5. Integration test on the private Tezos env
6. Amendment proposal on Tezos Agora

**Comment by daiki44** [comment]
@shogochiai 
When can we submit the amendment proposal of keccak256?
Also, when will we able to use it if the amendment is passed.

**Comment by shogochiai** [comment]
Submission requires an Implementation and rationale. I would finish implementing by Nov 1. Then I will write texts.

Using inside a private network is easy. Just after the implmentation finished, we can. Using on testnet as well is easy. Mainnet launch would be end of Feb.

**Comment by shogochiai** [comment]
## keccak256 OCaml implementation's evaluation

### Traget
https://github.com/xavierleroy/cryptokit

### Test result
![Screen Shot 2019-10-24 at 16 31 53](https://user-images.githubusercontent.com/4891004/67463034-a750a000-f67b-11e9-988e-5b571f4b596f.png)

![Screen Shot 2019-10-24 at 16 31 58](https://user-images.githubusercontent.com/4891004/67463043-aae42700-f67b-11e9-850c-634b497b067e.png)

### Reference
- [sha3-256 Online Executer](https://emn178.github.io/online-tools/sha3_256.html)
- [keccak256 Online Executer](https://emn178.github.io/online-tools/keccak_256.html)

**Comment by shogochiai** [comment]
Next action: Add `open Cryptokit; let keccak256 = (Hash.keccak 256) in` into `alpha_context.ml` and make `KECCAK256` as a new instrument.

**Comment by syuhei176** [comment]
We don't use keccak256 but use sha512 and sha256.
